version: '3.7'
services:
  db:
    image: postgres:13.6
    restart: always
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASSWORD:-password}
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${PG_USER:-postgres}" ]
      interval: 3s
      timeout: 3s
      retries: 5
    ports:
      - '5432:5432'
    stdin_open: true
    tty: true
    volumes:
      - db:/var/lib/postgresql/data
  todo:
    image: todo
    user: nonroot
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
    ports:
      - 8080:8080
volumes:
  db:
    driver: local