server:
  port: 8080

database:
  host: localhost
  port: 5432
  dbname: postgres
  dbuser: postgres
  dbpassword: password
  timezone: "Europe/Helsinki"

authz:
  endpoint: "http://127.0.0.1:8181/v1/data/authz"

authn:
  # See: https://developers.google.com/workspace/guides/create-credentials#oauth-client-id
  clientId: "<ADD YOUR CLIENT ID HERE>"
  notEnforced: true

frontend:
  endpoints:
    - "http://localhost:3000"
    - "http://localhost:3001"
